# Generated by Django 2.0.1 on 2018-04-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(max_length=10)),
                ('expired', models.DateField(max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LBook.Book')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], max_length=10)),
                ('mobileno', models.CharField(max_length=12)),
                ('emailId', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('user', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('student', 'student')], max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='Student',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LBook.Student'),
        ),
    ]
