# Generated by Django 2.0.1 on 2018-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0003_issuebook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
