# Generated by Django 2.0.1 on 2018-04-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0007_auto_20180410_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Registers',
        ),
    ]
