# Generated by Django 2.0.1 on 2018-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0008_auto_20180410_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='mailed_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
