# Generated by Django 2.0.1 on 2018-04-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LBook', '0009_issuebook_mailed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailDate', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LBook.Book')),
                ('issueBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LBook.IssueBook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LBook.Student')),
            ],
        ),
    ]
